// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package skyline_program

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_FeeConfig:
		value := new(FeeConfig)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as FeeConfig: %w", err)
		}
		return value, nil
	case Account_TokenIdGuard:
		value := new(TokenIdGuard)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TokenIdGuard: %w", err)
		}
		return value, nil
	case Account_TokenRegistry:
		value := new(TokenRegistry)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as TokenRegistry: %w", err)
		}
		return value, nil
	case Account_ValidatorSet:
		value := new(ValidatorSet)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as ValidatorSet: %w", err)
		}
		return value, nil
	case Account_Vault:
		value := new(Vault)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Vault: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_FeeConfig(accountData []byte) (*FeeConfig, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_FeeConfig {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_FeeConfig, binary.FormatDiscriminator(discriminator))
	}
	acc := new(FeeConfig)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type FeeConfig: %w", err)
	}
	return acc, nil
}

func ParseAccount_TokenIdGuard(accountData []byte) (*TokenIdGuard, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TokenIdGuard {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TokenIdGuard, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TokenIdGuard)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TokenIdGuard: %w", err)
	}
	return acc, nil
}

func ParseAccount_TokenRegistry(accountData []byte) (*TokenRegistry, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_TokenRegistry {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_TokenRegistry, binary.FormatDiscriminator(discriminator))
	}
	acc := new(TokenRegistry)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type TokenRegistry: %w", err)
	}
	return acc, nil
}

func ParseAccount_ValidatorSet(accountData []byte) (*ValidatorSet, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_ValidatorSet {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_ValidatorSet, binary.FormatDiscriminator(discriminator))
	}
	acc := new(ValidatorSet)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type ValidatorSet: %w", err)
	}
	return acc, nil
}

func ParseAccount_Vault(accountData []byte) (*Vault, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Vault {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Vault, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Vault)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Vault: %w", err)
	}
	return acc, nil
}
