// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains constants.

package skyline_program

// Constants defined in the IDL:

// Seed string used to derive BridgingRequest Program Derived Addresses (PDAs).
//
// This seed is combined with the sender's public key to create unique
// addresses for each bridging request account.
var BRIDGING_REQUEST_SEED = []byte{98, 114, 105, 100, 103, 105, 110, 103, 95, 114, 101, 113, 117, 101, 115, 116}

// Size of the account discriminator in bytes.
//
// The discriminator is an 8-byte prefix used by Anchor to identify
// account types and prevent account substitution attacks.
const DISC = uint32(0x8)

// Seed string used to derive FeeConfig PDA
var FEE_CONFIG_SEED = []byte{102, 101, 101, 95, 99, 111, 110, 102, 105, 103}

// Maximum number of validators allowed in the validator set.
//
// This constant defines the upper limit for the number of validators that can be
// included in the validator set. The limit is set to 128 to balance security,
// decentralization, and practical constraints.
const MAX_VALIDATORS = uint32(0x80)

// Maximum number of validators allowed to be added or removed in a single validator set change.
//
// This limit is imposed by Solana's transaction signing constraints.
// Each transaction can have a maximum of 10 validators added or removed.
const MAX_VALIDATORS_CHANGE = uint32(0xa)

// Minimum number of validators required for the bridge system.
//
// This ensures sufficient decentralization and security for the bridge.
// With fewer than 4 validators, the system would be vulnerable to
// various attack vectors and lack proper consensus mechanisms.
const MIN_VALIDATORS = uint32(0x4)

// Seed string used to derive TokenIdGuard PDA
var TOKEN_ID_GUARD_SEED = []byte{116, 111, 107, 101, 110, 95, 105, 100, 95, 103, 117, 97, 114, 100}

// Seed string used to derive TokenRegistry PDA
var TOKEN_REGISTRY_SEED = []byte{116, 111, 107, 101, 110, 95, 114, 101, 103, 105, 115, 116, 114, 121}

// Seed string used to derive the ValidatorSet Program Derived Address (PDA).
//
// This seed is used in conjunction with the program ID to generate
// a deterministic address for the validator set account.
var VALIDATOR_SET_SEED = []byte{118, 97, 108, 105, 100, 97, 116, 111, 114, 45, 115, 101, 116}

// Seed string used to derive Vault Program Derived Addresses (PDAs).
//
// This seed is combined with the vault address to create a unique address for the vault account.
var VAULT_SEED = []byte{118, 97, 117, 108, 116}
