// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package skyline_program

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "bridge_request" instruction.
// Create a cross-chain bridging request and transfer source tokens to vault. //  // This instruction creates a bridging request for transferring tokens to another chain. // The source tokens are either burned (if the vault is the mint authority) or transferred // to the vault account, and a request event is emitted that can be processed by validators // to mint/transfer equivalent tokens on the destination chain. //  // # Arguments // * `ctx` - The context containing accounts for the bridge request // * `amount` - The amount of tokens to bridge // * `receiver` - The receiver's address on the destination chain (variable length byte vector) // * `destination_chain` - The chain ID of the destination blockchain //  // # Errors // * `InsufficientFunds` - If the sender doesn't have enough tokens
func NewBridgeRequestInstruction(
	// Params:
	amountParam uint64,
	receiverParam string,
	destinationChainParam string,
	feesParam uint64,

	// Accounts:
	signerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	signersAtaAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	vaultAtaAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	treasuryAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeRequest[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `receiverParam`:
		err = enc__.Encode(receiverParam)
		if err != nil {
			return nil, errors.NewField("receiverParam", err)
		}
		// Serialize `destinationChainParam`:
		err = enc__.Encode(destinationChainParam)
		if err != nil {
			return nil, errors.NewField("destinationChainParam", err)
		}
		// Serialize `feesParam`:
		err = enc__.Encode(feesParam)
		if err != nil {
			return nil, errors.NewField("feesParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		// The user initiating the bridge request
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "signers_ata": Writable, Non-signer, Required
		// The user's associated token account for the tokens being bridged
		accounts__.Append(solanago.NewAccountMeta(signersAtaAccount, true, false))
		// Account 3 "vault": Writable, Non-signer, Required
		// The vault account
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 4 "vault_ata": Writable, Non-signer, Required
		// The vault associated token account for the tokens being bridged.
		// Only created if transfer branch is taken (not burn).
		// Manual creation is used instead of init_if_needed because the burn branch doesn't
		// need this account, avoiding unnecessary rent costs.
		accounts__.Append(solanago.NewAccountMeta(vaultAtaAccount, true, false))
		// Account 5 "mint": Writable, Non-signer, Required
		// The token mint for the tokens being bridged
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, false))
		// Account 6 "token_registry": Read-only, Non-signer, Required
		// The TokenRegistry PDA for this token id.
		//
		// Determines the bridge mechanic for this token:
		// - is_lock_unlock = true  → transfer tokens into vault (lock)
		// - is_lock_unlock = false → burn tokens from user's account
		//
		// Only tokens registered via register_lock_unlock_token or register_mint_burn_token
		// are permitted to be bridged. The account address is derived from the
		// stored token_id, and the stored mint must match `mint`.
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, false, false))
		// Account 7 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		// The token program for token operations (burn/transfer)
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 9 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		// The associated token program for creating token accounts
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 10 "fee_config": Read-only, Non-signer, Required
		// Fee configuration PDA — read to get fee amounts & treasury
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 11 "treasury": Writable, Non-signer, Required
		// Treasury — receives operational fee immediately
		accounts__.Append(solanago.NewAccountMeta(treasuryAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "bridge_transaction" instruction.
// Create or approve a bridging transaction. //  // This instruction creates or approves a bridging transaction for transferring tokens from the vault // to a recipient. The first call creates the transaction, and subsequent calls from validators approve it. // Once the consensus threshold is met, the tokens are automatically minted (if vault is mint authority) // or transferred from the vault to the recipient's associated token account, and the transaction account is closed. //  // # Arguments // * `ctx` - The context containing accounts for the bridging transaction // * `amount` - The amount of tokens to transfer to the recipient // * `batch_id` - The batch ID of the transaction (must be greater than last_batch_id) //  // # Errors // * `InvalidBatchId` - If the batch_id is not greater than the last_batch_id // * `InvalidReceiver` - If the receiver is the same as the payer // * `NoSignersProvided` - If no validator signers are provided // * `NotEnoughSigners` - If insufficient validators have signed (checked when threshold is met) // * `InvalidSigner` - If a signer is not in the validator set
func NewBridgeTransactionInstruction(
	payerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	instructionsAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeTransaction[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}

	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		// Pays rent for any recipient ATAs that need to be created (~0.002 SOL each)
		// and receives the `fee` lamport payout from the vault (relayer compensation,
		// analogous to EVM's `msg.sender`).
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// Validator set — holds threshold, registered signers, and last_batch_id.
		// `last_batch_id` is compared against the signed payload in the handler.
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "vault": Writable, Non-signer, Required
		// Bridge vault PDA — signing authority for mint_to and transfer_checked CPIs.
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 3 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		// SPL Token program.
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 4 "system_program": Read-only, Non-signer, Required
		// System program — required for ATA creation CPIs.
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 5 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		// Associated token program — required for ATA creation CPIs.
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 6 "instructions": Read-only, Non-signer, Required, Address: Sysvar1nstructions1111111111111111111111111
		// Instructions sysvar used to read and validate the preceding ed25519 ix.
		accounts__.Append(solanago.NewAccountMeta(instructionsAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "bridge_vsu" instruction.
// Create or approve a validator set update (VSU) for the bridge. //  // This instruction allows changing the set of validators that control bridge operations. // The first call creates a validator set change proposal, and subsequent calls from validators // approve the proposal. Requires approval from the current validator set meeting the consensus // threshold and maintains the same validation rules as initialization (unique validators, 4-10 count). //  // # Arguments // * `ctx` - The context containing accounts for creating or approving the validator set change // * `added` - Vector of new validator public keys to add // * `removed` - Vector of validator indexes to remove // * `batch_id` - The batch ID of the validator set change (must be greater than last_batch_id) //  // # Errors // * `MaxValidatorsExceeded` - If more than 10 validators would result from the change // * `MinValidatorsNotMet` - If fewer than 4 validators would result from the change // * `AddingExistingSigner` - If attempting to add a validator that already exists // * `InvalidBatchId` - If the batch_id is not greater than the last_batch_id // * `InvalidProposalHash` - If approving a proposal with a different hash than the original // * `NoSignersProvided` - If no validator signers are provided // * `NotEnoughSigners` - If insufficient current validators have signed (checked when threshold is met) // * `InvalidSigner` - If a signer is not in the current validator set
func NewBridgeVsuInstruction(
	// Params:
	addedParam []solanago.PublicKey,
	removedParam []solanago.PublicKey,
	batchIdParam uint64,

	// Accounts:
	payerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeVsu[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `addedParam`:
		err = enc__.Encode(addedParam)
		if err != nil {
			return nil, errors.NewField("addedParam", err)
		}
		// Serialize `removedParam`:
		err = enc__.Encode(removedParam)
		if err != nil {
			return nil, errors.NewField("removedParam", err)
		}
		// Serialize `batchIdParam`:
		err = enc__.Encode(batchIdParam)
		if err != nil {
			return nil, errors.NewField("batchIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		// The payer for any rent fees
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account to be updated
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "system_program": Read-only, Non-signer, Required
		// The system program
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "hot_wallet_increment" instruction.
// Top up the bridge vault hot wallet with either wSOL or native SOL. //  // Eligible mints: // - `WSOL_MINT` (`So11111111111111111111111111111111111111112`): // `transfer_checked` signer ATA → vault ATA. // - `NATIVE_SOL_MINT` (System Program ID sentinel): // `system_program::transfer` signer → vault PDA (lamports). //  // `signers_ata` and `vault_ata` are unused on the native-SOL branch and // can be filled with any placeholder (typically the System Program). //  // # Arguments // * `ctx`    - Instruction context // * `amount` - Raw amount to deposit (must be > 0). For wSOL: token base // units. For native SOL: lamports. //  // # Errors // * `InvalidAmount`       - `amount` is zero // * `InvalidMintToken`    - Mint is neither wSOL nor the native-SOL sentinel // * `InsufficientFunds`   - Signer lacks the requested wSOL / lamports // * `InvalidTokenAccount` - wSOL branch: signer's ATA failed validation // * `InvalidVault`        - wSOL branch: vault ATA address mismatch
func NewHotWalletIncrementInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	signerAccount solanago.PublicKey,
	signersAtaAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	vaultAtaAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_HotWalletIncrement[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		// The user depositing liquidity into the bridge hot wallet.
		// Pays rent if the vault ATA needs to be created (wSOL branch).
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "signers_ata": Writable, Non-signer, Required
		// and validated at runtime. Native-SOL branch — unused; pass any account
		// (e.g. the System Program) as a placeholder.
		accounts__.Append(solanago.NewAccountMeta(signersAtaAccount, true, false))
		// Account 2 "vault": Writable, Non-signer, Required
		// Bridge vault PDA. `mut` because the native-SOL branch credits its
		// lamport balance directly via `system_program::transfer`.
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 3 "vault_ata": Writable, Non-signer, Required
		// validated at runtime. Native-SOL branch — unused; placeholder allowed.
		accounts__.Append(solanago.NewAccountMeta(vaultAtaAccount, true, false))
		// Account 4 "mint": Read-only, Non-signer, Required
		// (native-SOL branch); enforced at runtime. For the native-SOL branch
		// this is the System Program account (since `NATIVE_SOL_MINT == System
		// Program ID`), matching the convention used by `bridge_transaction`.
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 5 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		// SPL Token program.
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		// System program — required for ATA creation CPI (wSOL branch) and the
		// native-SOL lamport transfer.
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 7 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		// Associated token program — required for ATA creation CPI.
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize" instruction.
// Initializes the full bridge system: // 1. ValidatorSet — validators, threshold, bump // 2. Vault        — bump // 3. FeeConfig    — operational fee, relayer fee estimate, treasury, authority // 4. ProgramConfig — on-chain version metadata (readable without a tx) //  // # Arguments // * `ctx`                  - The instruction context // * `validators`           - Vector of validator public keys // * `last_id`              - Last known batch ID (for replay protection) // * `min_operational_fee`  - Minimum bridge tip sent to treasury (lamports) // * `bridge_fee`           - Estimated destination chain gas cost (lamports) //  // # Errors // * `ValidatorsNotUnique`    - Duplicate validators provided // * `MaxValidatorsExceeded`  - Too many validators // * `MinValidatorsNotMet`    - Too few validators
func NewInitializeInstruction(
	// Params:
	validatorsParam []solanago.PublicKey,
	lastIdParam *uint64,
	minOperationalFeeParam uint64,
	bridgeFeeParam uint64,

	// Accounts:
	signerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	programConfigAccount solanago.PublicKey,
	treasuryAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `validatorsParam`:
		err = enc__.Encode(validatorsParam)
		if err != nil {
			return nil, errors.NewField("validatorsParam", err)
		}
		// Serialize `lastIdParam` (optional):
		{
			if lastIdParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("lastIdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("lastIdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(lastIdParam)
				if err != nil {
					return nil, errors.NewField("lastIdParam", err)
				}
			}
		}
		// Serialize `minOperationalFeeParam`:
		err = enc__.Encode(minOperationalFeeParam)
		if err != nil {
			return nil, errors.NewField("minOperationalFeeParam", err)
		}
		// Serialize `bridgeFeeParam`:
		err = enc__.Encode(bridgeFeeParam)
		if err != nil {
			return nil, errors.NewField("bridgeFeeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		// The signer who is initializing the bridge system
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account to be initialized
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "vault": Writable, Non-signer, Required
		// The vault account
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 3 "fee_config": Writable, Non-signer, Required
		// The fee config PDA — created here, one per program
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, true, false))
		// Account 4 "program_config": Writable, Non-signer, Required
		// Global program version / deploy metadata — one per program, read-only for integrations.
		accounts__.Append(solanago.NewAccountMeta(programConfigAccount, true, false))
		// Account 5 "treasury": Read-only, Non-signer, Required
		// The treasury account that will receive operational fees
		accounts__.Append(solanago.NewAccountMeta(treasuryAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "register_lock_unlock_token" instruction.
func NewRegisterLockUnlockTokenInstruction(
	// Params:
	tokenIdParam uint16,
	minBridgingAmountParam uint64,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
	tokenIdGuardAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RegisterLockUnlockToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `tokenIdParam`:
		err = enc__.Encode(tokenIdParam)
		if err != nil {
			return nil, errors.NewField("tokenIdParam", err)
		}
		// Serialize `minBridgingAmountParam`:
		err = enc__.Encode(minBridgingAmountParam)
		if err != nil {
			return nil, errors.NewField("minBridgingAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Writable, Signer, Required
		// The bridge admin.
		// Must match fee_config.authority — enforced by constraint below.
		// Pays rent for TokenRegistry and TokenIdGuard PDAs.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, true, true))
		// Account 1 "fee_config": Read-only, Non-signer, Required
		// Read-only. Used solely to validate authority == fee_config.authority.
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		// The pre-existing SPL mint being registered (e.g. WSOL, USDC).
		// Anchor validates this is a real, initialized SPL mint account.
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "token_registry": Writable, Non-signer, Required
		// TokenRegistry PDA — one per token_id.
		//
		// This is the Solana-idiomatic "map entry": given any token_id, the
		// registry for that token is always at a deterministic address:
		// PDA([TOKEN_REGISTRY_SEED, token_id.to_le_bytes()])
		//
		// Anchor's `init` rejects creation if the account already exists,
		// making double-registration of the same token_id impossible.
		// PDA: [TOKEN_REGISTRY_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, true, false))
		// Account 4 "token_id_guard": Writable, Non-signer, Required
		// TokenIdGuard PDA — one per token_id.
		//
		// Compatibility sentinel derived by token_id.
		// PDA: [TOKEN_ID_GUARD_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenIdGuardAccount, true, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "register_mint_burn_token" instruction.
// Register a new SPL mint as a MintBurn bridgeable token. //  // Creates the mint, assigns vault as mint_authority, attaches Metaplex // metadata, and writes TokenRegistry + TokenIdGuard PDAs. //  // Only callable by the bridge authority. //  // # Arguments // * `ctx`      - Instruction context // * `token_id` - Unique gateway-compatible uint16 identifier // * `decimals` - Decimal precision of the new mint (e.g. 6 or 9) // * `min_bridging_amount` - Minimum raw token amount allowed per bridge_request // * `name`     - Token name for Metaplex metadata // * `symbol`   - Token symbol for Metaplex metadata // * `uri`      - Metadata URI (IPFS / Arweave JSON) //  // # Errors // * `CustomError::Unauthorized`    - Signer is not the bridge authority
func NewRegisterMintBurnTokenInstruction(
	// Params:
	tokenIdParam uint16,
	decimalsParam uint8,
	minBridgingAmountParam uint64,
	nameParam string,
	symbolParam string,
	uriParam string,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
	tokenIdGuardAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	metadataProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RegisterMintBurnToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `tokenIdParam`:
		err = enc__.Encode(tokenIdParam)
		if err != nil {
			return nil, errors.NewField("tokenIdParam", err)
		}
		// Serialize `decimalsParam`:
		err = enc__.Encode(decimalsParam)
		if err != nil {
			return nil, errors.NewField("decimalsParam", err)
		}
		// Serialize `minBridgingAmountParam`:
		err = enc__.Encode(minBridgingAmountParam)
		if err != nil {
			return nil, errors.NewField("minBridgingAmountParam", err)
		}
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
		// Serialize `symbolParam`:
		err = enc__.Encode(symbolParam)
		if err != nil {
			return nil, errors.NewField("symbolParam", err)
		}
		// Serialize `uriParam`:
		err = enc__.Encode(uriParam)
		if err != nil {
			return nil, errors.NewField("uriParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Writable, Signer, Required
		// Bridge authority — must match fee_config.authority.
		// Pays rent for: new Mint, Metadata, TokenRegistry, TokenIdGuard.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, true, true))
		// Account 1 "fee_config": Read-only, Non-signer, Required
		// Read-only. Validates authority
		// PDA: [FEE_CONFIG_SEED]
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 2 "vault": Read-only, Non-signer, Required
		// Vault PDA — will be set as mint_authority + freeze_authority for the new mint.
		// This is what gives the bridge exclusive minting rights.
		// PDA: [VAULT_SEED]
		//
		// it is only used as an authority pubkey in CPI calls.
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, false, false))
		// Account 3 "mint": Writable, Signer, Required
		// The brand-new SPL mint created by this instruction.
		// Client generates the keypair off-chain and passes it as a signer.
		// mint_authority and freeze_authority → vault PDA.
		// decimals → provided by caller (typically 6 or 9).
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, true))
		// Account 4 "metadata": Writable, Non-signer, Required
		// Metaplex metadata account for the new mint.
		// Derived by Metaplex program — seeds are managed by the metadata CPI.
		//
		// inside the Metaplex create_metadata_accounts_v3 CPI call.
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, true, false))
		// Account 5 "token_registry": Writable, Non-signer, Required
		// One PDA per token_id — enforces token_id uniqueness across the registry.
		// Anchor init fails with AlreadyInUse if this token_id was already registered.
		// PDA: [TOKEN_REGISTRY_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, true, false))
		// Account 6 "token_id_guard": Writable, Non-signer, Required
		// One PDA per token_id — retained for compatibility with existing clients.
		// Anchor init fails with AlreadyInUse if this token_id is already taken.
		// PDA: [TOKEN_ID_GUARD_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenIdGuardAccount, true, false))
		// Account 7 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "metadata_program": Read-only, Non-signer, Required, Address: metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
		accounts__.Append(solanago.NewAccountMeta(metadataProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "rent": Read-only, Non-signer, Required, Address: SysvarRent111111111111111111111111111111111
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_fee_config" instruction.
// Update the fee configuration for the bridge. //  // This instruction allows the authority to update the fee configuration parameters for the bridge, // including the minimum operational fee, bridge fee, minimum bridging amount, treasury address, and // relayer address. The authority can choose to update any subset of these parameters, and the instruction // will validate the new values and emit an event with the updated configuration. //  // # Arguments // * `ctx` - The context containing accounts for updating the fee configuration // * `min_operational_fee` - Optional new minimum operational fee (lamports) // * `bridge_fee` - Optional new bridge fee (lamports) // * `update_treasury` - Optional flag indicating whether to update the treasury address //  // # Errors // * `InvalidTreasury` - If the new treasury address is invalid
func NewUpdateFeeConfigInstruction(
	// Params:
	minOperationalFeeParam *uint64,
	bridgeFeeParam *uint64,
	updateTreasuryParam *bool,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	newTreasuryAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateFeeConfig[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `minOperationalFeeParam` (optional):
		{
			if minOperationalFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minOperationalFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minOperationalFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minOperationalFeeParam)
				if err != nil {
					return nil, errors.NewField("minOperationalFeeParam", err)
				}
			}
		}
		// Serialize `bridgeFeeParam` (optional):
		{
			if bridgeFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("bridgeFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("bridgeFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(bridgeFeeParam)
				if err != nil {
					return nil, errors.NewField("bridgeFeeParam", err)
				}
			}
		}
		// Serialize `updateTreasuryParam` (optional):
		{
			if updateTreasuryParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("updateTreasuryParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("updateTreasuryParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(updateTreasuryParam)
				if err != nil {
					return nil, errors.NewField("updateTreasuryParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 1 "fee_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, true, false))
		// Account 2 "new_treasury": Read-only, Non-signer, Required
		// New treasury account — only needed when updating treasury.
		accounts__.Append(solanago.NewAccountMeta(newTreasuryAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_min_bridging_amount" instruction.
// Update the minimum bridging amount for a registered token. //  // Only callable by the bridge authority. The token must already be registered // via `register_lock_unlock_token` or `register_mint_burn_token`. //  // # Arguments // * `token_id`            - Gateway-compatible identifier of the registered token // * `min_bridging_amount` - New minimum raw token amount per `bridge_request` //  // # Errors // * `CustomError::Unauthorized` - Signer is not the bridge authority
func NewUpdateMinBridgingAmountInstruction(
	// Params:
	tokenIdParam uint16,
	minBridgingAmountParam uint64,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateMinBridgingAmount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `tokenIdParam`:
		err = enc__.Encode(tokenIdParam)
		if err != nil {
			return nil, errors.NewField("tokenIdParam", err)
		}
		// Serialize `minBridgingAmountParam`:
		err = enc__.Encode(minBridgingAmountParam)
		if err != nil {
			return nil, errors.NewField("minBridgingAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Read-only, Signer, Required
		// The bridge admin. Must match `fee_config.authority`.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 1 "fee_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 2 "token_registry": Writable, Non-signer, Required
		// TokenRegistry PDA for the given `token_id`.
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_program_version" instruction.
// Updates `ProgramConfig.version_string` to match a new deployment. //  // Program upgrades do not write to this PDA; the bridge authority must call this // after upgrading so integrations reading the account see the correct version. //  // # Arguments // * `version_string` - Semver display string (at most 32 bytes) //  // # Errors // * `Unauthorized`         - Signer is not `ProgramConfig.authority` // * `VersionStringTooLong`   - `version_string` exceeds storage limit
func NewUpdateProgramVersionInstruction(
	// Params:
	versionStringParam string,

	// Accounts:
	authorityAccount solanago.PublicKey,
	programConfigAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateProgramVersion[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `versionStringParam`:
		err = enc__.Encode(versionStringParam)
		if err != nil {
			return nil, errors.NewField("versionStringParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 1 "program_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(programConfigAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
