// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package skyline_program

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "bridge_request" instruction.
// Create a cross-chain bridging request and transfer source tokens to vault. //  // This instruction creates a bridging request for transferring tokens to another chain. // The source tokens are either burned (if the vault is the mint authority) or transferred // to the vault account, and a request event is emitted that can be processed by validators // to mint/transfer equivalent tokens on the destination chain. //  // # Arguments // * `ctx` - The context containing accounts for the bridge request // * `amount` - The amount of tokens to bridge // * `receiver` - The receiver's address on the destination chain (variable length byte vector) // * `destination_chain` - The chain ID of the destination blockchain //  // # Errors // * `InsufficientFunds` - If the sender doesn't have enough tokens
func NewBridgeRequestInstruction(
	// Params:
	amountParam uint64,
	receiverParam []byte,
	destinationChainParam uint8,
	feesParam uint64,

	// Accounts:
	signerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	signersAtaAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	vaultAtaAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	treasuryAccount solanago.PublicKey,
	relayerAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeRequest[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `receiverParam`:
		err = enc__.Encode(receiverParam)
		if err != nil {
			return nil, errors.NewField("receiverParam", err)
		}
		// Serialize `destinationChainParam`:
		err = enc__.Encode(destinationChainParam)
		if err != nil {
			return nil, errors.NewField("destinationChainParam", err)
		}
		// Serialize `feesParam`:
		err = enc__.Encode(feesParam)
		if err != nil {
			return nil, errors.NewField("feesParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		// The user initiating the bridge request
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "signers_ata": Writable, Non-signer, Required
		// The user's associated token account for the tokens being bridged
		accounts__.Append(solanago.NewAccountMeta(signersAtaAccount, true, false))
		// Account 3 "vault": Writable, Non-signer, Required
		// The vault account
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 4 "vault_ata": Writable, Non-signer, Required
		// The vault associated token account for the tokens being bridged.
		// Only created if transfer branch is taken (not burn).
		// Manual creation is used instead of init_if_needed because the burn branch doesn't
		// need this account, avoiding unnecessary rent costs.
		accounts__.Append(solanago.NewAccountMeta(vaultAtaAccount, true, false))
		// Account 5 "mint": Writable, Non-signer, Required
		// The token mint for the tokens being bridged
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, false))
		// Account 6 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		// The token program for token operations (burn/transfer)
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 7 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 8 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		// The associated token program for creating token accounts
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 9 "fee_config": Read-only, Non-signer, Required
		// Fee configuration PDA — read to get fee amounts & treasury
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 10 "treasury": Writable, Non-signer, Required
		// Treasury — receives operational fee immediately
		accounts__.Append(solanago.NewAccountMeta(treasuryAccount, true, false))
		// Account 11 "relayer": Writable, Non-signer, Required
		// Relayer — receives bridge_fee immediately
		accounts__.Append(solanago.NewAccountMeta(relayerAccount, true, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "bridge_transaction" instruction.
// Create or approve a bridging transaction. //  // This instruction creates or approves a bridging transaction for transferring tokens from the vault // to a recipient. The first call creates the transaction, and subsequent calls from validators approve it. // Once the consensus threshold is met, the tokens are automatically minted (if vault is mint authority) // or transferred from the vault to the recipient's associated token account, and the transaction account is closed. //  // # Arguments // * `ctx` - The context containing accounts for the bridging transaction // * `amount` - The amount of tokens to transfer to the recipient // * `batch_id` - The batch ID of the transaction (must be greater than last_batch_id) //  // # Errors // * `InvalidBatchId` - If the batch_id is not greater than the last_batch_id // * `InvalidReceiver` - If the receiver is the same as the payer // * `NoSignersProvided` - If no validator signers are provided // * `SignerAlreadyApproved` - If a signer has already approved this transaction // * `NotEnoughSigners` - If insufficient validators have signed (checked when threshold is met) // * `InvalidSigner` - If a signer is not in the validator set
func NewBridgeTransactionInstruction(
	// Params:
	amountParam uint64,
	batchIdParam uint64,

	// Accounts:
	payerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	bridgingTransactionAccount solanago.PublicKey,
	mintTokenAccount solanago.PublicKey,
	recipientAccount solanago.PublicKey,
	recipientAtaAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	vaultAtaAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeTransaction[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
		// Serialize `batchIdParam`:
		err = enc__.Encode(batchIdParam)
		if err != nil {
			return nil, errors.NewField("batchIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		// The payer for any associated token account creation
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account for consensus validation
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "bridging_transaction": Writable, Non-signer, Required
		// The bridging transaction account to be created
		accounts__.Append(solanago.NewAccountMeta(bridgingTransactionAccount, true, false))
		// Account 3 "mint_token": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintTokenAccount, true, false))
		// Account 4 "recipient": Read-only, Non-signer, Required
		// The recipient of the bridged tokens
		accounts__.Append(solanago.NewAccountMeta(recipientAccount, false, false))
		// Account 5 "recipient_ata": Writable, Non-signer, Required
		// The recipient's associated token account for the mint
		// Validated to be the canonical ATA address, created manually after threshold check
		accounts__.Append(solanago.NewAccountMeta(recipientAtaAccount, true, false))
		// Account 6 "vault": Writable, Non-signer, Required
		// The vault account
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 7 "vault_ata": Writable, Non-signer, Required
		// The vault associated token account for the mint
		// Validated to be the canonical ATA address
		accounts__.Append(solanago.NewAccountMeta(vaultAtaAccount, true, false))
		// Account 8 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		// The token program for minting operations
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "associated_token_program": Read-only, Non-signer, Required, Address: ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL
		// The associated token program for creating token accounts
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "bridge_vsu" instruction.
// Create or approve a validator set update (VSU) for the bridge. //  // This instruction allows changing the set of validators that control bridge operations. // The first call creates a validator set change proposal, and subsequent calls from validators // approve the proposal. Requires approval from the current validator set meeting the consensus // threshold and maintains the same validation rules as initialization (unique validators, 4-10 count). //  // # Arguments // * `ctx` - The context containing accounts for creating or approving the validator set change // * `added` - Vector of new validator public keys to add // * `removed` - Vector of validator indexes to remove // * `batch_id` - The batch ID of the validator set change (must be greater than last_batch_id) //  // # Errors // * `MaxValidatorsExceeded` - If more than 10 validators would result from the change // * `MinValidatorsNotMet` - If fewer than 4 validators would result from the change // * `AddingExistingSigner` - If attempting to add a validator that already exists // * `InvalidBatchId` - If the batch_id is not greater than the last_batch_id // * `InvalidProposalHash` - If approving a proposal with a different hash than the original // * `NoSignersProvided` - If no validator signers are provided // * `NotEnoughSigners` - If insufficient current validators have signed (checked when threshold is met) // * `InvalidSigner` - If a signer is not in the current validator set
func NewBridgeVsuInstruction(
	// Params:
	addedParam []solanago.PublicKey,
	removedParam []solanago.PublicKey,
	batchIdParam uint64,

	// Accounts:
	payerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	validatorSetChangeAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_BridgeVsu[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `addedParam`:
		err = enc__.Encode(addedParam)
		if err != nil {
			return nil, errors.NewField("addedParam", err)
		}
		// Serialize `removedParam`:
		err = enc__.Encode(removedParam)
		if err != nil {
			return nil, errors.NewField("removedParam", err)
		}
		// Serialize `batchIdParam`:
		err = enc__.Encode(batchIdParam)
		if err != nil {
			return nil, errors.NewField("batchIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "payer": Writable, Signer, Required
		// The payer for any associated token account creation
		accounts__.Append(solanago.NewAccountMeta(payerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account to be updated
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "validator_set_change": Writable, Non-signer, Required
		// The validator set change account to be created
		accounts__.Append(solanago.NewAccountMeta(validatorSetChangeAccount, true, false))
		// Account 3 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "initialize" instruction.
// Initializes the full bridge system: // 1. ValidatorSet — validators, threshold, bump // 2. Vault        — bump // 3. FeeConfig    — operational fee, relayer fee estimate, treasury, authority //  // # Arguments // * `ctx`                  - The instruction context // * `validators`           - Vector of validator public keys // * `last_id`              - Last known batch ID (for replay protection) // * `min_operational_fee`  - Minimum bridge tip sent to treasury (lamports) // * `bridge_fee`           - Estimated destination chain gas cost (lamports) // * `min_bridging_amount`  - Minimum amount of tokens that can be bridged (in smallest unit, e.g. lamports for SOL) //  // # Errors // * `ValidatorsNotUnique`    - Duplicate validators provided // * `MaxValidatorsExceeded`  - Too many validators // * `MinValidatorsNotMet`    - Too few validators
func NewInitializeInstruction(
	// Params:
	validatorsParam []solanago.PublicKey,
	lastIdParam *uint64,
	minOperationalFeeParam uint64,
	bridgeFeeParam uint64,
	minBridgingAmountParam uint64,
	currencyTokenIdParam uint16,

	// Accounts:
	signerAccount solanago.PublicKey,
	validatorSetAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	treasuryAccount solanago.PublicKey,
	relayerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Initialize[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `validatorsParam`:
		err = enc__.Encode(validatorsParam)
		if err != nil {
			return nil, errors.NewField("validatorsParam", err)
		}
		// Serialize `lastIdParam` (optional):
		{
			if lastIdParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("lastIdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("lastIdParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(lastIdParam)
				if err != nil {
					return nil, errors.NewField("lastIdParam", err)
				}
			}
		}
		// Serialize `minOperationalFeeParam`:
		err = enc__.Encode(minOperationalFeeParam)
		if err != nil {
			return nil, errors.NewField("minOperationalFeeParam", err)
		}
		// Serialize `bridgeFeeParam`:
		err = enc__.Encode(bridgeFeeParam)
		if err != nil {
			return nil, errors.NewField("bridgeFeeParam", err)
		}
		// Serialize `minBridgingAmountParam`:
		err = enc__.Encode(minBridgingAmountParam)
		if err != nil {
			return nil, errors.NewField("minBridgingAmountParam", err)
		}
		// Serialize `currencyTokenIdParam`:
		err = enc__.Encode(currencyTokenIdParam)
		if err != nil {
			return nil, errors.NewField("currencyTokenIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "signer": Writable, Signer, Required
		// The signer who is initializing the bridge system
		accounts__.Append(solanago.NewAccountMeta(signerAccount, true, true))
		// Account 1 "validator_set": Writable, Non-signer, Required
		// The validator set account to be initialized
		accounts__.Append(solanago.NewAccountMeta(validatorSetAccount, true, false))
		// Account 2 "vault": Writable, Non-signer, Required
		// The vault account
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, true, false))
		// Account 3 "fee_config": Writable, Non-signer, Required
		// The fee config PDA — created here, one per program
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, true, false))
		// Account 4 "treasury": Read-only, Non-signer, Required
		// The treasury account that will receive operational fees
		accounts__.Append(solanago.NewAccountMeta(treasuryAccount, false, false))
		// Account 5 "relayer": Read-only, Non-signer, Required
		// Relayer account — receives bridge fees directly
		accounts__.Append(solanago.NewAccountMeta(relayerAccount, false, false))
		// Account 6 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "register_lock_unlock_token" instruction.
func NewRegisterLockUnlockTokenInstruction(
	// Params:
	tokenIdParam uint16,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
	tokenIdGuardAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RegisterLockUnlockToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `tokenIdParam`:
		err = enc__.Encode(tokenIdParam)
		if err != nil {
			return nil, errors.NewField("tokenIdParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Writable, Signer, Required
		// The admin who owns the bridge.
		// Must match fee_config.authority — enforced by constraint below.
		// Pays rent for TokenRegistry and TokenIdGuard PDAs.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, true, true))
		// Account 1 "fee_config": Read-only, Non-signer, Required
		// Read-only. Used solely to validate that authority == fee_config.authority.
		// PDA: [FEE_CONFIG_SEED]
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 2 "mint": Read-only, Non-signer, Required
		// The pre-existing SPL mint being registered (e.g. USDC, WSOL).
		// NOT created here — must already exist on-chain.
		// Anchor validates this is a real, initialized SPL mint account.
		accounts__.Append(solanago.NewAccountMeta(mintAccount, false, false))
		// Account 3 "token_registry": Writable, Non-signer, Required
		// One PDA per mint. Anchor init fails if it already exists.
		// That failure surfaces as MintAlreadyRegistered (via init constraint).
		// PDA: [TOKEN_REGISTRY_SEED, mint.key()]
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, true, false))
		// Account 4 "token_id_guard": Writable, Non-signer, Required
		// One PDA per token_id. Anchor init fails if it already exists.
		// That failure prevents two mints sharing the same token_id,
		// which would corrupt destination-chain routing.
		// PDA: [TOKEN_ID_GUARD_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenIdGuardAccount, true, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		// The system program for account creation
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "register_mint_burn_token" instruction.
// Register a new SPL mint as a MintBurn bridgeable token. //  // Creates the mint, assigns vault as mint_authority, attaches Metaplex // metadata, and writes TokenRegistry + TokenIdGuard PDAs. //  // Only callable by the bridge authority. //  // # Arguments // * `ctx`      - Instruction context // * `token_id` - Unique gateway-compatible uint16 identifier // * `decimals` - Decimal precision of the new mint (e.g. 6 or 9) // * `name`     - Token name for Metaplex metadata // * `symbol`   - Token symbol for Metaplex metadata // * `uri`      - Metadata URI (IPFS / Arweave JSON) //  // # Errors // * `CustomError::Unauthorized`    - Signer is not the bridge authority // * `CustomError::CurrencyTokenId` - token_id is reserved for native currency
func NewRegisterMintBurnTokenInstruction(
	// Params:
	tokenIdParam uint16,
	decimalsParam uint8,
	nameParam string,
	symbolParam string,
	uriParam string,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	vaultAccount solanago.PublicKey,
	mintAccount solanago.PublicKey,
	metadataAccount solanago.PublicKey,
	tokenRegistryAccount solanago.PublicKey,
	tokenIdGuardAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	metadataProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RegisterMintBurnToken[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `tokenIdParam`:
		err = enc__.Encode(tokenIdParam)
		if err != nil {
			return nil, errors.NewField("tokenIdParam", err)
		}
		// Serialize `decimalsParam`:
		err = enc__.Encode(decimalsParam)
		if err != nil {
			return nil, errors.NewField("decimalsParam", err)
		}
		// Serialize `nameParam`:
		err = enc__.Encode(nameParam)
		if err != nil {
			return nil, errors.NewField("nameParam", err)
		}
		// Serialize `symbolParam`:
		err = enc__.Encode(symbolParam)
		if err != nil {
			return nil, errors.NewField("symbolParam", err)
		}
		// Serialize `uriParam`:
		err = enc__.Encode(uriParam)
		if err != nil {
			return nil, errors.NewField("uriParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Writable, Signer, Required
		// Bridge authority — must match fee_config.authority.
		// Pays rent for: new Mint, Metadata, TokenRegistry, TokenIdGuard.
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, true, true))
		// Account 1 "fee_config": Read-only, Non-signer, Required
		// Read-only. Validates authority and provides currency_token_id guard value.
		// PDA: [FEE_CONFIG_SEED]
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, false, false))
		// Account 2 "vault": Read-only, Non-signer, Required
		// Vault PDA — will be set as mint_authority + freeze_authority for the new mint.
		// This is what gives the bridge exclusive minting rights.
		// PDA: [VAULT_SEED]
		//
		// it is only used as an authority pubkey in CPI calls.
		accounts__.Append(solanago.NewAccountMeta(vaultAccount, false, false))
		// Account 3 "mint": Writable, Signer, Required
		// The brand-new SPL mint created by this instruction.
		// Client generates the keypair off-chain and passes it as a signer.
		// mint_authority and freeze_authority → vault PDA.
		// decimals → provided by caller (typically 6 or 9).
		accounts__.Append(solanago.NewAccountMeta(mintAccount, true, true))
		// Account 4 "metadata": Writable, Non-signer, Required
		// Metaplex metadata account for the new mint.
		// Derived by Metaplex program — seeds are managed by the metadata CPI.
		//
		// inside the Metaplex create_metadata_accounts_v3 CPI call.
		accounts__.Append(solanago.NewAccountMeta(metadataAccount, true, false))
		// Account 5 "token_registry": Writable, Non-signer, Required
		// One PDA per mint — enforces mint uniqueness across the registry.
		// Anchor init fails with AlreadyInUse if this mint was already registered.
		// PDA: [TOKEN_REGISTRY_SEED, mint.key()]
		accounts__.Append(solanago.NewAccountMeta(tokenRegistryAccount, true, false))
		// Account 6 "token_id_guard": Writable, Non-signer, Required
		// One PDA per token_id — enforces token_id uniqueness across the registry.
		// Anchor init fails with AlreadyInUse if this token_id is already taken.
		// PDA: [TOKEN_ID_GUARD_SEED, token_id.to_le_bytes()]
		accounts__.Append(solanago.NewAccountMeta(tokenIdGuardAccount, true, false))
		// Account 7 "token_program": Read-only, Non-signer, Required, Address: TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "metadata_program": Read-only, Non-signer, Required, Address: metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s
		accounts__.Append(solanago.NewAccountMeta(metadataProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "rent": Read-only, Non-signer, Required, Address: SysvarRent111111111111111111111111111111111
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "update_fee_config" instruction.
// Update the fee configuration for the bridge. //  // This instruction allows the authority to update the fee configuration parameters for the bridge, // including the minimum operational fee, bridge fee, minimum bridging amount, treasury address, and // relayer address. The authority can choose to update any subset of these parameters, and the instruction // will validate the new values and emit an event with the updated configuration. //  // # Arguments // * `ctx` - The context containing accounts for updating the fee configuration // * `min_operational_fee` - Optional new minimum operational fee (lamports) // * `bridge_fee` - Optional new bridge fee (lamports) // * `min_bridging_amount` - Optional new minimum bridging amount (in smallest unit, e.g. lamports for SOL) // * `update_treasury` - Optional flag indicating whether to update the treasury address // * `update_relayer` - Optional flag indicating whether to update the relayer address //  // # Errors // * `InvalidRelayer` - If the new relayer address is invalid // * `InvalidTreasury` - If the new treasury address is invalid
func NewUpdateFeeConfigInstruction(
	// Params:
	minOperationalFeeParam *uint64,
	bridgeFeeParam *uint64,
	minBridgingAmountParam *uint64,
	updateTreasuryParam *bool,
	updateRelayerParam *bool,

	// Accounts:
	authorityAccount solanago.PublicKey,
	feeConfigAccount solanago.PublicKey,
	newTreasuryAccount solanago.PublicKey,
	newRelayerAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_UpdateFeeConfig[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `minOperationalFeeParam` (optional):
		{
			if minOperationalFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minOperationalFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minOperationalFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minOperationalFeeParam)
				if err != nil {
					return nil, errors.NewField("minOperationalFeeParam", err)
				}
			}
		}
		// Serialize `bridgeFeeParam` (optional):
		{
			if bridgeFeeParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("bridgeFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("bridgeFeeParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(bridgeFeeParam)
				if err != nil {
					return nil, errors.NewField("bridgeFeeParam", err)
				}
			}
		}
		// Serialize `minBridgingAmountParam` (optional):
		{
			if minBridgingAmountParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("minBridgingAmountParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("minBridgingAmountParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(minBridgingAmountParam)
				if err != nil {
					return nil, errors.NewField("minBridgingAmountParam", err)
				}
			}
		}
		// Serialize `updateTreasuryParam` (optional):
		{
			if updateTreasuryParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("updateTreasuryParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("updateTreasuryParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(updateTreasuryParam)
				if err != nil {
					return nil, errors.NewField("updateTreasuryParam", err)
				}
			}
		}
		// Serialize `updateRelayerParam` (optional):
		{
			if updateRelayerParam == nil {
				err = enc__.WriteOption(false)
				if err != nil {
					return nil, errors.NewOption("updateRelayerParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
			} else {
				err = enc__.WriteOption(true)
				if err != nil {
					return nil, errors.NewOption("updateRelayerParam", fmt.Errorf("error while encoding optionality: %w", err))
				}
				err = enc__.Encode(updateRelayerParam)
				if err != nil {
					return nil, errors.NewField("updateRelayerParam", err)
				}
			}
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(authorityAccount, false, true))
		// Account 1 "fee_config": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(feeConfigAccount, true, false))
		// Account 2 "new_treasury": Read-only, Non-signer, Required
		// New treasury account — only needed when updating treasury.
		accounts__.Append(solanago.NewAccountMeta(newTreasuryAccount, false, false))
		// Account 3 "new_relayer": Read-only, Non-signer, Required
		// New relayer account — only needed when updating relayer.
		accounts__.Append(solanago.NewAccountMeta(newRelayerAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}
