// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package skyline_program

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("CkTNcuk9EELmuR65eCfzKfz8XpDvJ27FPFHauGHVD1E9")
