// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package skyline_program

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Event emitted when a bridge request is created.
//
// This event is emitted when a user initiates a cross-chain token transfer.
// The event contains all the information needed for validators to process
// the request and execute the corresponding transaction on the destination chain.
type BridgeRequestEvent struct {
	// Public key of the user who initiated the bridge request
	Sender solanago.PublicKey `json:"sender"`

	// Amount of tokens to be bridged to the destination chain
	Amount uint64 `json:"amount"`

	// Receiver's address on the destination chain (variable length byte vector)
	// This format accommodates various address formats across different blockchains
	Receiver []byte `json:"receiver"`

	// Chain ID identifying the destination blockchain network
	DestinationChain uint8 `json:"destinationChain"`

	// Public key of the token mint being bridged
	MintToken solanago.PublicKey `json:"mintToken"`

	// The batch request ID associated with this bridge request
	BatchRequestId uint64 `json:"batchRequestId"`

	// The fee amount for the relayer to process this bridge request
	BridgeFee uint64 `json:"bridgeFee"`

	// The operational fee for the bridge to maintain its operations
	OperationalFee uint64 `json:"operationalFee"`
}

func (obj BridgeRequestEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Sender`:
	err = encoder.Encode(obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `Receiver`:
	err = encoder.Encode(obj.Receiver)
	if err != nil {
		return errors.NewField("Receiver", err)
	}
	// Serialize `DestinationChain`:
	err = encoder.Encode(obj.DestinationChain)
	if err != nil {
		return errors.NewField("DestinationChain", err)
	}
	// Serialize `MintToken`:
	err = encoder.Encode(obj.MintToken)
	if err != nil {
		return errors.NewField("MintToken", err)
	}
	// Serialize `BatchRequestId`:
	err = encoder.Encode(obj.BatchRequestId)
	if err != nil {
		return errors.NewField("BatchRequestId", err)
	}
	// Serialize `BridgeFee`:
	err = encoder.Encode(obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Serialize `OperationalFee`:
	err = encoder.Encode(obj.OperationalFee)
	if err != nil {
		return errors.NewField("OperationalFee", err)
	}
	return nil
}

func (obj BridgeRequestEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BridgeRequestEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BridgeRequestEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Sender`:
	err = decoder.Decode(&obj.Sender)
	if err != nil {
		return errors.NewField("Sender", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `Receiver`:
	err = decoder.Decode(&obj.Receiver)
	if err != nil {
		return errors.NewField("Receiver", err)
	}
	// Deserialize `DestinationChain`:
	err = decoder.Decode(&obj.DestinationChain)
	if err != nil {
		return errors.NewField("DestinationChain", err)
	}
	// Deserialize `MintToken`:
	err = decoder.Decode(&obj.MintToken)
	if err != nil {
		return errors.NewField("MintToken", err)
	}
	// Deserialize `BatchRequestId`:
	err = decoder.Decode(&obj.BatchRequestId)
	if err != nil {
		return errors.NewField("BatchRequestId", err)
	}
	// Deserialize `BridgeFee`:
	err = decoder.Decode(&obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Deserialize `OperationalFee`:
	err = decoder.Decode(&obj.OperationalFee)
	if err != nil {
		return errors.NewField("OperationalFee", err)
	}
	return nil
}

func (obj *BridgeRequestEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BridgeRequestEvent: %w", err)
	}
	return nil
}

func UnmarshalBridgeRequestEvent(buf []byte) (*BridgeRequestEvent, error) {
	obj := new(BridgeRequestEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Represents a bridging transaction that transfers tokens to a recipient.
//
// The `BridgingTransaction` account tracks a pending token transfer that requires
// validator consensus. Once enough validators have approved the transaction (meeting
// the threshold), the tokens are automatically transferred or minted to the recipient,
// and the account is closed.
//
// # Fields
//
// * `id` - Unique identifier for the transaction (same as the account's key)
// * `amount` - The amount of tokens to transfer to the recipient
// * `receiver` - The public key of the recipient on the destination chain
// * `mint_token` - The public key of the token mint being bridged
// * `signers` - List of validator public keys that have approved this transaction
// * `bump` - Bump seed for the PDA derivation
// * `batch_id` - The batch ID of this transaction (must be greater than last_batch_id)
type BridgingTransaction struct {
	// Unique identifier for the transaction
	Id solanago.PublicKey `json:"id"`

	// The amount of tokens to transfer to the recipient
	Amount uint64 `json:"amount"`

	// The public key of the recipient on the destination chain
	Receiver solanago.PublicKey `json:"receiver"`

	// The public key of the token mint being bridged
	MintToken solanago.PublicKey `json:"mintToken"`

	// List of validator public keys that have approved this transaction
	Signers []solanago.PublicKey `json:"signers"`

	// Bump seed for the Program Derived Address (PDA)
	Bump uint8 `json:"bump"`

	// The batch ID of this transaction (must be greater than last_batch_id)
	BatchId uint64 `json:"batchId"`
}

func (obj BridgingTransaction) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Id`:
	err = encoder.Encode(obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `Receiver`:
	err = encoder.Encode(obj.Receiver)
	if err != nil {
		return errors.NewField("Receiver", err)
	}
	// Serialize `MintToken`:
	err = encoder.Encode(obj.MintToken)
	if err != nil {
		return errors.NewField("MintToken", err)
	}
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `BatchId`:
	err = encoder.Encode(obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj BridgingTransaction) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding BridgingTransaction: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *BridgingTransaction) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Id`:
	err = decoder.Decode(&obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `Receiver`:
	err = decoder.Decode(&obj.Receiver)
	if err != nil {
		return errors.NewField("Receiver", err)
	}
	// Deserialize `MintToken`:
	err = decoder.Decode(&obj.MintToken)
	if err != nil {
		return errors.NewField("MintToken", err)
	}
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `BatchId`:
	err = decoder.Decode(&obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj *BridgingTransaction) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling BridgingTransaction: %w", err)
	}
	return nil
}

func UnmarshalBridgingTransaction(buf []byte) (*BridgingTransaction, error) {
	obj := new(BridgingTransaction)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Stores protocol-level fee configuration.
// Created once by the bridge authority via init_fee_config.
// Can be updated via update_fee_config.
type FeeConfig struct {
	// Minimum fee that goes to the bridge treasury (operational tip)
	MinOperationalFee uint64 `json:"minOperationalFee"`

	// Estimated fee to refund the relayer for destination chain gas
	BridgeFee uint64 `json:"bridgeFee"`

	// Minimum token amount allowed per bridge request
	MinBridgingAmount uint64 `json:"minBridgingAmount"`

	// The token ID reserved for native SOL bridging
	CurrencyTokenId uint16 `json:"currencyTokenId"`

	// Treasury account where operational fees are sent
	Treasury solanago.PublicKey `json:"treasury"`

	// Relayer account — receives bridge_fee directly per bridge request
	Relayer solanago.PublicKey `json:"relayer"`

	// Who is allowed to update this config (bridge authority)
	Authority solanago.PublicKey `json:"authority"`

	// PDA bump
	Bump uint8 `json:"bump"`
}

func (obj FeeConfig) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MinOperationalFee`:
	err = encoder.Encode(obj.MinOperationalFee)
	if err != nil {
		return errors.NewField("MinOperationalFee", err)
	}
	// Serialize `BridgeFee`:
	err = encoder.Encode(obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Serialize `MinBridgingAmount`:
	err = encoder.Encode(obj.MinBridgingAmount)
	if err != nil {
		return errors.NewField("MinBridgingAmount", err)
	}
	// Serialize `CurrencyTokenId`:
	err = encoder.Encode(obj.CurrencyTokenId)
	if err != nil {
		return errors.NewField("CurrencyTokenId", err)
	}
	// Serialize `Treasury`:
	err = encoder.Encode(obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Serialize `Relayer`:
	err = encoder.Encode(obj.Relayer)
	if err != nil {
		return errors.NewField("Relayer", err)
	}
	// Serialize `Authority`:
	err = encoder.Encode(obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj FeeConfig) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeConfig: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeConfig) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MinOperationalFee`:
	err = decoder.Decode(&obj.MinOperationalFee)
	if err != nil {
		return errors.NewField("MinOperationalFee", err)
	}
	// Deserialize `BridgeFee`:
	err = decoder.Decode(&obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Deserialize `MinBridgingAmount`:
	err = decoder.Decode(&obj.MinBridgingAmount)
	if err != nil {
		return errors.NewField("MinBridgingAmount", err)
	}
	// Deserialize `CurrencyTokenId`:
	err = decoder.Decode(&obj.CurrencyTokenId)
	if err != nil {
		return errors.NewField("CurrencyTokenId", err)
	}
	// Deserialize `Treasury`:
	err = decoder.Decode(&obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Deserialize `Relayer`:
	err = decoder.Decode(&obj.Relayer)
	if err != nil {
		return errors.NewField("Relayer", err)
	}
	// Deserialize `Authority`:
	err = decoder.Decode(&obj.Authority)
	if err != nil {
		return errors.NewField("Authority", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *FeeConfig) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeConfig: %w", err)
	}
	return nil
}

func UnmarshalFeeConfig(buf []byte) (*FeeConfig, error) {
	obj := new(FeeConfig)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when fee config values are updated by the authority.
type FeeConfigUpdatedEvent struct {
	// Minimum operational fee (SOL lamports)
	MinOperationalFee uint64 `json:"minOperationalFee"`

	// Bridge fee paid to relayer (SOL lamports)
	BridgeFee uint64 `json:"bridgeFee"`

	// Minimum bridging amount
	MinBridgingAmount uint64 `json:"minBridgingAmount"`

	// Treasury address
	Treasury solanago.PublicKey `json:"treasury"`

	// Relayer address
	Relayer solanago.PublicKey `json:"relayer"`
}

func (obj FeeConfigUpdatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `MinOperationalFee`:
	err = encoder.Encode(obj.MinOperationalFee)
	if err != nil {
		return errors.NewField("MinOperationalFee", err)
	}
	// Serialize `BridgeFee`:
	err = encoder.Encode(obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Serialize `MinBridgingAmount`:
	err = encoder.Encode(obj.MinBridgingAmount)
	if err != nil {
		return errors.NewField("MinBridgingAmount", err)
	}
	// Serialize `Treasury`:
	err = encoder.Encode(obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Serialize `Relayer`:
	err = encoder.Encode(obj.Relayer)
	if err != nil {
		return errors.NewField("Relayer", err)
	}
	return nil
}

func (obj FeeConfigUpdatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding FeeConfigUpdatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *FeeConfigUpdatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `MinOperationalFee`:
	err = decoder.Decode(&obj.MinOperationalFee)
	if err != nil {
		return errors.NewField("MinOperationalFee", err)
	}
	// Deserialize `BridgeFee`:
	err = decoder.Decode(&obj.BridgeFee)
	if err != nil {
		return errors.NewField("BridgeFee", err)
	}
	// Deserialize `MinBridgingAmount`:
	err = decoder.Decode(&obj.MinBridgingAmount)
	if err != nil {
		return errors.NewField("MinBridgingAmount", err)
	}
	// Deserialize `Treasury`:
	err = decoder.Decode(&obj.Treasury)
	if err != nil {
		return errors.NewField("Treasury", err)
	}
	// Deserialize `Relayer`:
	err = decoder.Decode(&obj.Relayer)
	if err != nil {
		return errors.NewField("Relayer", err)
	}
	return nil
}

func (obj *FeeConfigUpdatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling FeeConfigUpdatedEvent: %w", err)
	}
	return nil
}

func UnmarshalFeeConfigUpdatedEvent(buf []byte) (*FeeConfigUpdatedEvent, error) {
	obj := new(FeeConfigUpdatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when a LockUnlock token is registered.
// Gateway parity: TokenRegistered event in Gateway.sol
//
// LockUnlock path:
// mint pre-exists (e.g. USDC, WSOL)
// vault ATA receives/releases tokens
// no new SPL mint is created
// is_lock_unlock always true
type LockUnlockTokenRegisteredEvent struct {
	// Gateway-compatible uint16 identifier.
	// Destination chain uses this to route events.
	TokenId uint16 `json:"tokenId"`

	// The pre-existing SPL mint being registered.
	Mint solanago.PublicKey `json:"mint"`
}

func (obj LockUnlockTokenRegisteredEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TokenId`:
	err = encoder.Encode(obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	return nil
}

func (obj LockUnlockTokenRegisteredEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding LockUnlockTokenRegisteredEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *LockUnlockTokenRegisteredEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TokenId`:
	err = decoder.Decode(&obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	return nil
}

func (obj *LockUnlockTokenRegisteredEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling LockUnlockTokenRegisteredEvent: %w", err)
	}
	return nil
}

func UnmarshalLockUnlockTokenRegisteredEvent(buf []byte) (*LockUnlockTokenRegisteredEvent, error) {
	obj := new(LockUnlockTokenRegisteredEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Emitted when a MintBurn token is registered.
// Gateway parity: TokenRegistered event in Gateway.sol
//
// MintBurn path:
// new SPL mint CREATED during this instruction
// vault PDA is set as mint_authority
// tokens burned on bridge_request
// tokens minted on bridge_transaction
// is_lock_unlock always false
type MintBurnTokenRegisteredEvent struct {
	// Gateway-compatible uint16 identifier.
	TokenId uint16 `json:"tokenId"`

	// The NEWLY CREATED SPL mint.
	// Client generated the keypair — this is its public key.
	Mint solanago.PublicKey `json:"mint"`

	// On-chain token name stored in Metaplex metadata.
	Name string `json:"name"`

	// On-chain token symbol stored in Metaplex metadata.
	Symbol string `json:"symbol"`
}

func (obj MintBurnTokenRegisteredEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TokenId`:
	err = encoder.Encode(obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Name`:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Serialize `Symbol`:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	return nil
}

func (obj MintBurnTokenRegisteredEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding MintBurnTokenRegisteredEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *MintBurnTokenRegisteredEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TokenId`:
	err = decoder.Decode(&obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return errors.NewField("Name", err)
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return errors.NewField("Symbol", err)
	}
	return nil
}

func (obj *MintBurnTokenRegisteredEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling MintBurnTokenRegisteredEvent: %w", err)
	}
	return nil
}

func UnmarshalMintBurnTokenRegisteredEvent(buf []byte) (*MintBurnTokenRegisteredEvent, error) {
	obj := new(MintBurnTokenRegisteredEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TokenIdGuard struct {
	// The mint assigned to this token_id.
	// Stored for auditability — lets you trace token_id → mint on-chain.
	Mint solanago.PublicKey `json:"mint"`

	// Stored to avoid recomputing.
	Bump uint8 `json:"bump"`
}

func (obj TokenIdGuard) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj TokenIdGuard) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TokenIdGuard: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TokenIdGuard) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *TokenIdGuard) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TokenIdGuard: %w", err)
	}
	return nil
}

func UnmarshalTokenIdGuard(buf []byte) (*TokenIdGuard, error) {
	obj := new(TokenIdGuard)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type TokenRegistry struct {
	// Unique token ID assigned by the bridge authority at registration.
	TokenId uint16 `json:"tokenId"`

	// The SPL mint this registry entry corresponds to.
	// LockUnlock: pre-existing mint passed by admin.
	// MintBurn:   newly created mint from register_mint_burn_token.
	Mint solanago.PublicKey `json:"mint"`

	// Determines token movement direction at bridge_request / bridge_transaction.
	// true  → Lock/Unlock: transfer to/from vault ATA
	// false → Mint/Burn:   burn from user ATA / mint to user ATA
	// Declared once by authority at registration — immutable thereafter.
	IsLockUnlock bool `json:"isLockUnlock"`

	// Stored to avoid recomputing in CPI calls.
	Bump uint8 `json:"bump"`
}

func (obj TokenRegistry) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TokenId`:
	err = encoder.Encode(obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Serialize `Mint`:
	err = encoder.Encode(obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Serialize `IsLockUnlock`:
	err = encoder.Encode(obj.IsLockUnlock)
	if err != nil {
		return errors.NewField("IsLockUnlock", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj TokenRegistry) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TokenRegistry: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TokenRegistry) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TokenId`:
	err = decoder.Decode(&obj.TokenId)
	if err != nil {
		return errors.NewField("TokenId", err)
	}
	// Deserialize `Mint`:
	err = decoder.Decode(&obj.Mint)
	if err != nil {
		return errors.NewField("Mint", err)
	}
	// Deserialize `IsLockUnlock`:
	err = decoder.Decode(&obj.IsLockUnlock)
	if err != nil {
		return errors.NewField("IsLockUnlock", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *TokenRegistry) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TokenRegistry: %w", err)
	}
	return nil
}

func UnmarshalTokenRegistry(buf []byte) (*TokenRegistry, error) {
	obj := new(TokenRegistry)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Event emitted when a bridging transaction is successfully executed.
//
// This event is emitted after a bridging transaction has received sufficient
// validator approvals and the tokens have been transferred or minted to the recipient.
type TransactionExecutedEvent struct {
	// The unique identifier of the transaction that was executed
	TransactionId solanago.PublicKey `json:"transactionId"`

	// The batch ID of the executed transaction
	BatchId uint64 `json:"batchId"`
}

func (obj TransactionExecutedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `TransactionId`:
	err = encoder.Encode(obj.TransactionId)
	if err != nil {
		return errors.NewField("TransactionId", err)
	}
	// Serialize `BatchId`:
	err = encoder.Encode(obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj TransactionExecutedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding TransactionExecutedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *TransactionExecutedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `TransactionId`:
	err = decoder.Decode(&obj.TransactionId)
	if err != nil {
		return errors.NewField("TransactionId", err)
	}
	// Deserialize `BatchId`:
	err = decoder.Decode(&obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj *TransactionExecutedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling TransactionExecutedEvent: %w", err)
	}
	return nil
}

func UnmarshalTransactionExecutedEvent(buf []byte) (*TransactionExecutedEvent, error) {
	obj := new(TransactionExecutedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Represents a pending validator set update that requires consensus.
//
// The `ValidatorDelta` account tracks a proposed change to the validator set that
// requires approval from the current validators. Once enough validators have approved
// the proposal (meeting the threshold), the changes are applied to the validator set,
// and the account is closed.
//
// # Fields
//
// * `id` - Unique identifier for the validator set change (same as the account's key)
// * `added` - List of new validator public keys to add to the validator set
// * `removed` - List of validator indices to remove from the validator set
// * `bump` - Bump seed for the PDA derivation
// * `batch_id` - The batch ID of this validator set change (must be greater than last_batch_id)
// * `signers` - List of validator public keys that have approved this change
// * `proposal_hash` - Hash of the proposal to ensure all validators approve the same change
type ValidatorDelta struct {
	// Unique identifier for the validator set change
	Id solanago.PublicKey `json:"id"`

	// List of new validator public keys to add (max 10 per change)
	Added []solanago.PublicKey `json:"added"`

	// List of validator public keys to remove (max 10 per change)
	Removed []solanago.PublicKey `json:"removed"`

	// Bump seed for the Program Derived Address (PDA)
	Bump uint8 `json:"bump"`

	// The batch ID of this validator set change (must be greater than last_batch_id)
	BatchId uint64 `json:"batchId"`

	// List of validator public keys that have approved this change
	Signers []solanago.PublicKey `json:"signers"`

	// Hash of the proposal to ensure all validators approve the same change
	ProposalHash [32]uint8 `json:"proposalHash"`
}

func (obj ValidatorDelta) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Id`:
	err = encoder.Encode(obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Serialize `Added`:
	err = encoder.Encode(obj.Added)
	if err != nil {
		return errors.NewField("Added", err)
	}
	// Serialize `Removed`:
	err = encoder.Encode(obj.Removed)
	if err != nil {
		return errors.NewField("Removed", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `BatchId`:
	err = encoder.Encode(obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Serialize `ProposalHash`:
	err = encoder.Encode(obj.ProposalHash)
	if err != nil {
		return errors.NewField("ProposalHash", err)
	}
	return nil
}

func (obj ValidatorDelta) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ValidatorDelta: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ValidatorDelta) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Id`:
	err = decoder.Decode(&obj.Id)
	if err != nil {
		return errors.NewField("Id", err)
	}
	// Deserialize `Added`:
	err = decoder.Decode(&obj.Added)
	if err != nil {
		return errors.NewField("Added", err)
	}
	// Deserialize `Removed`:
	err = decoder.Decode(&obj.Removed)
	if err != nil {
		return errors.NewField("Removed", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `BatchId`:
	err = decoder.Decode(&obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Deserialize `ProposalHash`:
	err = decoder.Decode(&obj.ProposalHash)
	if err != nil {
		return errors.NewField("ProposalHash", err)
	}
	return nil
}

func (obj *ValidatorDelta) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ValidatorDelta: %w", err)
	}
	return nil
}

func UnmarshalValidatorDelta(buf []byte) (*ValidatorDelta, error) {
	obj := new(ValidatorDelta)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Represents the validator set that controls bridge operations.
//
// The `ValidatorSet` account stores the list of validators authorized to perform
// critical bridge operations and the consensus threshold required for approval.
// This account is initialized once and can be updated through the validator set
// change instruction with proper consensus.
//
// # Fields
//
// * `signers` - Vector of validator public keys (max 128 validators)
// * `threshold` - Number of signatures required for consensus (automatically calculated)
// * `bump` - Bump seed for the PDA derivation
// * `last_batch_id` - The last processed batch ID to prevent replay attacks
// * `bridge_request_count` - Total count of bridge requests processed
type ValidatorSet struct {
	// List of validator public keys that can sign bridge operations
	// Maximum length is constrained by `MAX_VALIDATORS` constant
	Signers []solanago.PublicKey `json:"signers"`

	// Consensus threshold - number of validator signatures required
	// Automatically calculated using the formula: num_signers - floor((num_signers - 1) / 3)
	Threshold uint8 `json:"threshold"`

	// Bump seed for the Program Derived Address (PDA)
	Bump uint8 `json:"bump"`

	// Last batch ID processed to prevent replay attacks and ensure sequential processing
	LastBatchId uint64 `json:"lastBatchId"`

	// Total count of bridge requests processed since initialization
	BridgeRequestCount uint64 `json:"bridgeRequestCount"`
}

func (obj ValidatorSet) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Signers`:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Serialize `Threshold`:
	err = encoder.Encode(obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `LastBatchId`:
	err = encoder.Encode(obj.LastBatchId)
	if err != nil {
		return errors.NewField("LastBatchId", err)
	}
	// Serialize `BridgeRequestCount`:
	err = encoder.Encode(obj.BridgeRequestCount)
	if err != nil {
		return errors.NewField("BridgeRequestCount", err)
	}
	return nil
}

func (obj ValidatorSet) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ValidatorSet: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ValidatorSet) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return errors.NewField("Signers", err)
	}
	// Deserialize `Threshold`:
	err = decoder.Decode(&obj.Threshold)
	if err != nil {
		return errors.NewField("Threshold", err)
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `LastBatchId`:
	err = decoder.Decode(&obj.LastBatchId)
	if err != nil {
		return errors.NewField("LastBatchId", err)
	}
	// Deserialize `BridgeRequestCount`:
	err = decoder.Decode(&obj.BridgeRequestCount)
	if err != nil {
		return errors.NewField("BridgeRequestCount", err)
	}
	return nil
}

func (obj *ValidatorSet) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ValidatorSet: %w", err)
	}
	return nil
}

func UnmarshalValidatorSet(buf []byte) (*ValidatorSet, error) {
	obj := new(ValidatorSet)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Event emitted when the validator set is successfully updated.
//
// This event is emitted after a validator set change proposal has received
// sufficient validator approvals and the changes have been applied to the validator set.
type ValidatorSetUpdatedEvent struct {
	// The new list of validator signers after the update
	NewSigners []solanago.PublicKey `json:"newSigners"`

	// The new consensus threshold for the validator set
	NewThreshold uint8 `json:"newThreshold"`

	// The batch ID associated with the validator set update
	BatchId uint64 `json:"batchId"`
}

func (obj ValidatorSetUpdatedEvent) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `NewSigners`:
	err = encoder.Encode(obj.NewSigners)
	if err != nil {
		return errors.NewField("NewSigners", err)
	}
	// Serialize `NewThreshold`:
	err = encoder.Encode(obj.NewThreshold)
	if err != nil {
		return errors.NewField("NewThreshold", err)
	}
	// Serialize `BatchId`:
	err = encoder.Encode(obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj ValidatorSetUpdatedEvent) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding ValidatorSetUpdatedEvent: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *ValidatorSetUpdatedEvent) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `NewSigners`:
	err = decoder.Decode(&obj.NewSigners)
	if err != nil {
		return errors.NewField("NewSigners", err)
	}
	// Deserialize `NewThreshold`:
	err = decoder.Decode(&obj.NewThreshold)
	if err != nil {
		return errors.NewField("NewThreshold", err)
	}
	// Deserialize `BatchId`:
	err = decoder.Decode(&obj.BatchId)
	if err != nil {
		return errors.NewField("BatchId", err)
	}
	return nil
}

func (obj *ValidatorSetUpdatedEvent) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling ValidatorSetUpdatedEvent: %w", err)
	}
	return nil
}

func UnmarshalValidatorSetUpdatedEvent(buf []byte) (*ValidatorSetUpdatedEvent, error) {
	obj := new(ValidatorSetUpdatedEvent)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

// Represents the vault account that holds bridged tokens.
//
// The `Vault` account is a Program Derived Address (PDA) that serves as the authority
// for token operations. It can be set as the mint authority for tokens, allowing it to
// mint tokens on the destination chain, or it can hold tokens in an associated token
// account for transfer operations.
//
// # Fields
//
// * `address` - The public key of the vault account (same as the account's key)
// * `bump` - Bump seed for the PDA derivation
type Vault struct {
	// Bump seed for the Program Derived Address (PDA)
	Bump uint8 `json:"bump"`
}

func (obj Vault) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj Vault) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Vault: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Vault) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	return nil
}

func (obj *Vault) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Vault: %w", err)
	}
	return nil
}

func UnmarshalVault(buf []byte) (*Vault, error) {
	obj := new(Vault)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
